hadd -f output_data_driven_qcdbkg_diphoreweighted_2016PreVFP.root output_data_driven_bkg_2016PreVFP.root output_ggjets_reweighted_2016PreVFP.root
hadd -f	output_data_driven_qcdbkg_diphoreweighted_2016PostVFP.root output_data_driven_bkg_2016PostVFP.root output_ggjets_reweighted_2016PostVFP.root
hadd -f	output_data_driven_qcdbkg_diphoreweighted_2017.root output_data_driven_bkg_2017.root output_ggjets_reweighted_2017.root
hadd -f	output_data_driven_qcdbkg_diphoreweighted_2018.root output_data_driven_bkg_2018.root output_ggjets_reweighted_2018.root
